### ISSUE TITLE
Item stats don't line up with table on sheet

### ISSUE THREAD

**Issue by Zero101011** [Siggysaw/arcane-arcade-fallout#73]
Foundry V12.331, AA Fallout version 0.0.46, tested without modules & with.

after changing stats of the claw item provided in community item compendium to reflect the deathclaw's attack the table provided on the status panel of the sheet doesn't reflect the stat changes, remaining at the base damage of 2d4, clicking the dice number does however roll the correct damage. this is purely a cosmetic bug and easily missed if you only look at the combat panel when rolling

![image](https://github.com/user-attachments/assets/62a2f241-9aa9-47fb-a4d0-6b2f6a2ca49b)

note that I added an extra damage type to test if that would be reflected either.

various other parts of the table accurately update, for example the AP, STR req and crit DV, however the crit damage doesnt display whatsoever.

![image](https://github.com/user-attachments/assets/dba4b3c2-a708-45f5-8eaf-e9714d54239d)

**Comment by Siggysaw** [comment]
Damage Box has been removed to streamline the NPC box, 
Enemy weapons were reverted to default values during an update and will need to be re-edited to match the proper damage values, but should be working otherwise! 
![image](https://github.com/user-attachments/assets/2ef91d2a-1919-4644-8125-2e64167b167c)
